### ISSUE TITLE
Wrong commit in Octopus Deploy release notes

### ISSUE THREAD

**Issue by zerrvox** [kolonialno/velo-action#155]
I have been creating a few releases from Tienda the last week, and I noticed that it seems there is a bug when github action creates the release in Octopus Deploy. If to commits are made to the main branch (only one in tienda creating releases) very close to each other (same second) the earlier release will link to the wrong commit in the release noted.

**Example** 
https://octopusdeploy.prod.nube.tech/app#/Spaces-1/projects/tienda/deployments/releases/aee4283690371bb54b1642f2d8e7f0ff45cf7214 Should link to https://github.com/kolonialno/tienda/commit/aee4283690371bb54b1642f2d8e7f0ff45cf7214 commited at 2022-07-19T11:24:55Z but it links to  https://github.com/kolonialno/tienda/commit/313c9c88d666ea1c22c615dc4703908bf36ea9ed commited at 2022-07-19T11:24:55Z

If relevant here is the link to the later release https://octopusdeploy.prod.nube.tech/app#/Spaces-1/projects/tienda/deployments/releases/313c9c88d666ea1c22c615dc4703908bf36ea9ed

I had a look at the code for the action and this might be a bug with how the environment variables are set for the container in Github actions.

**Comment by zerrvox** [comment]
I have logged an issue with Github here (probably not open for others to see) https://support.github.com/ticket/personal/0/1715449

**Comment by zerrvox** [comment]
Also the github action with the wrong environment variables is this https://github.com/kolonialno/tienda/runs/7408240082?check_suite_focus=true

**Comment by RmStorm** [comment]
This was fixed long ago here https://github.com/kolonialno/velo-action/pull/42 Currently it's using the variable called [github sha](https://github.com/kolonialno/velo-action/blob/main/velo_action/octopus/release.py#L140) which points to the head at the time of workflow running. Not to the commit that triggered the workflow. This behaviour is documented, [here](https://github.com/orgs/community/discussions/26325) for example... but it's not great.

**Comment by RmStorm** [comment]
I originially fixed it by parsing the sha from the checked out repo since that one is always correct: https://github.com/kolonialno/velo-action/pull/42/files#diff-99d42ce933c64acf0d7c92c64413bb5a0ccb2f2a5e831218c3882dbcb4b8da3eR38-R42

**Comment by thor** [comment]
This [issue has been imported into Linear](https://linear.app/odacom/issue/CP-474) with the ID CP-474 under the assumption that it is part of Cloud Platform's area. Indeed, we hope it is! :fire:

---

:warning: Should this issue not have imported? Shout out @thor or let us know in`#cloud-platform`. :bow:
