### ISSUE TITLE
Sometimes the GH api has timestamps out of order.

### ISSUE THREAD

**Issue by RmStorm** [kolonialno/velo-action#159]
Install `gh` cli and `jq` and run this command to verify:
`gh api repos/kolonialno/alma/actions/jobs/7648595458 | jq .steps[10]`

The output right now is this:
```json
{
  "name": "Post Run actions/setup-python@v4",
  "status": "completed",
  "conclusion": "success",
  "number": 15,
  "started_at": "2022-08-03T11:12:51.000+02:00",
  "completed_at": "2022-08-03T11:12:49.000+02:00"
}
```
The `completed_at` field is simply earlier then the `started_at` field.

**Comment by RmStorm** [comment]
These timestamps are not properly visible in the regular GH interface, see here:
https://github.com/kolonialno/alma/runs/7648595458?check_suite_focus=true
or here for the logs:
https://pipelines.actions.githubusercontent.com/serviceHosts/d16d5f64-fa80-4e2a-8a47-a24536313795/_apis/pipelines/1/runs/101292/signedlogcontent/5?urlExpires=2022-08-03T10%3A36%3A55.7246604Z&urlSigningMethod=HMACV1&urlSignature=MjS%2B3fQuW%2BpM1fEYEcU6hyRXeFwMBXcyrcdjbQLTE7Q%3D

**Comment by thor** [comment]
This [issue has been imported into Linear](https://linear.app/odacom/issue/CP-475) with the ID CP-475 under the assumption that it is part of Cloud Platform's area. Indeed, we hope it is! :fire:

---

:warning: Should this issue not have imported? Shout out @thor or let us know in`#cloud-platform`. :bow:
